const orderActionType = {
  FETCH_ALL_ORDERS_START: 'FETCH_ALL_ORDERS_START',
  FETCH_ALL_ORDERS_SUCCESS: 'FETCH_ALL_ORDERS_SUCCESS',
  FETCH_ALL_ORDERS_FAILED: 'FETCH_ALL_ORDERS_FAILED',
  UPDATE_ORDER_STATUS_SUCCESS: 'UPDATE_ORDER_STATUS_SUCCESS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};

export default orderActionType;
