const productActionTypes = {
  FETCH_ALL_PRODUCT: 'FETCH_ALL_PRODUCT',
  FETCH_ALL_PRODUCT_START: 'FETCH_ALL_PRODUCT_START',
  FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
  FETCH_ALL_PRODUCT_FAILED: 'FETCH_ALL_PRODUCT_FAILED',
  SET_PRODUCT_CURRENT_PAGE: 'SET_PRODUCT_CURRENT_PAGE',
  SET_PRODUCT_CURRENT_SORT: 'SET_PRODUCT_CURRENT_SORT',
  SET_PRODUCT_CURRENT_CATEGORIES: 'SET_PRODUCT_CURRENT_CATEGORIES',
  FETCH_PRODUCT_ADVANCE_START: 'FETCH_PRODUCT_ADVANCE_START',
  FETCH_PRODUCT_ADVANCE_FAILED: 'FETCH_PRODUCT_ADVANCE_FAILED',
  FETCH_PRODUCT_ADVANCE_SUCCESS: 'FETCH_PRODUCT_ADVANCE_SUCCESS',
};

export default productActionTypes;
